version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `pr` directory
    directory: '/pr'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `build` directory
    directory: "/build"
    schedule:
    # Check the npm registry for updates every day (weekdays)
      interval: "daily"
