name: 'PR'
description: 'PR build'
author: 'Likvido'
inputs:
  access-token:
    description: 'github token'
    required: true
  image-name:
    description: 'image name'
    required: true
  docker-file-path:
    description: 'docker file path'
    required: true
  docker-target:
    description: 'docker target'
    required: true
  working-directory:
    description: 'working directory'
    required: false
    default: '.'
  src-replacement:
    description: "Indicates file path adjustement to match source control useful for docker build"
    required: false
    default: ""
  tests-report-name:
    description: "Test report name"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'  
  color: 'orange'