name: 'PR'
description: 'PR build'
author: 'Likvido'
inputs:
  access-token:
    description: 'github token'
    required: true
  image-name:
    description: 'image name'
    required: true
  docker-file-path:
    description: 'docker file path'
    required: true
  docker-target:
    description: 'docker target'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'  
  color: 'orange'